-- ======================================================
-- ESQUEMA DA TABELA 'cardapio' PARA O SUPABASE (SESI)
-- ======================================================
-- Execute este script no SQL Editor do seu projeto Supabase
-- para criar a tabela e popular com os dados de exemplo.

CREATE TABLE IF NOT EXISTS public.cardapio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_semana TEXT UNIQUE NOT NULL, -- 'segunda', 'terca', 'quarta', 'quinta', 'sexta'
    
    -- Café da Manhã
    cafe_prato TEXT,
    cafe_suco TEXT,
    cafe_fruta TEXT,
    
    -- Almoço
    almoco_prato TEXT,
    almoco_salada TEXT,
    almoco_sobremesa TEXT,

    -- Café da Tarde / Lanche
    lanche_prato TEXT,
    lanche_bebida TEXT,
    lanche_fruta TEXT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilita Leitura Pública (Row Level Security - RLS)
ALTER TABLE public.cardapio ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura pública do cardápio"
ON public.cardapio FOR SELECT
USING (true);

CREATE POLICY "Permitir inserção e atualização pública do cardápio"
ON public.cardapio FOR ALL
USING (true);

-- ======================================================
-- INSERÇÃO / ATUALIZAÇÃO DOS DADOS DE CARDÁPIO
-- ======================================================
INSERT INTO public.cardapio (dia_semana, cafe_prato, cafe_suco, cafe_fruta, almoco_prato, almoco_salada, almoco_sobremesa, lanche_prato, lanche_bebida, lanche_fruta)
VALUES
  ('segunda', 'Leite com Cacaueira & Pão Integral com Requeijão', 'Suco de Laranja Natural', 'Banana Prata', 'Arroz Soltinho, Feijão Carioca, Iscas de Frango Grelhado & Purê de Batata', 'Salada de Alface Crocante com Cenoura Ralada', 'Maçã Fuji', 'Bolo Caseiro de Cenoura com Cobertura & Leite', 'Leite', 'Melancia em Cubos'),
  ('terca', 'Vitamina de Morango & Torrada com Geleia', 'Suco de Uva Integral', 'Mamão', 'Arroz Integral, Feijão Preto, Carne Moída com Vagem & Farofa de Milho', 'Tomate fatiado com Pepino', 'Gelatina de Morango', 'Pão de Queijo Assado & Suco Natural', 'Suco Natural', 'Uva sem semente'),
  ('quarta', 'Achocolatado Quente & Broinha de Milho', 'Suco de Goiaba', 'Pera', 'Macarrão Penne ao Molho Bolonhesa ou Molho Branco & Iscas de Carne', 'Beterraba Cozida com Cheiro Verde', 'Salada de Frutas', 'Sanduíche Natural de Frango com Requeijão', 'Suco', 'Banana'),
  ('quinta', 'Leite com Cereais & Pão Francês com Manteiga', 'Suco de Maracujá', 'Melão', 'Arroz com Cheiro Verde, Feijão Carioca, Strogonoff de Frango & Batata Palha Assada', 'Salada de Repolho Roxo e Brócolis', 'Banana Assada com Canela', 'Bisnaguinha Integral com Queijo & Suco', 'Suco', 'Maçã Verde'),
  ('sexta', 'Iogurte Natural com Granola & Pão de Batata', 'Suco de Abacaxi com Hortelã', 'Tangerina', 'Feijoada Leve SESI (com Lombo e Paio), Arroz Branco, Couve Refogada & Laranja', 'Vinaigrette Suave', 'Docinho de Leite em Pó', 'Pipoca Salgada Assada & Suco de Manga', 'Suco de Manga', 'Melancia')
ON CONFLICT (dia_semana) DO UPDATE SET
  cafe_prato = EXCLUDED.cafe_prato,
  cafe_suco = EXCLUDED.cafe_suco,
  cafe_fruta = EXCLUDED.cafe_fruta,
  almoco_prato = EXCLUDED.almoco_prato,
  almoco_salada = EXCLUDED.almoco_salada,
  almoco_sobremesa = EXCLUDED.almoco_sobremesa,
  lanche_prato = EXCLUDED.lanche_prato,
  lanche_bebida = EXCLUDED.lanche_bebida,
  lanche_fruta = EXCLUDED.lanche_fruta,
  updated_at = NOW();
